chore: rename first and second to 1st and 2nd

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -56,7 +56,7 @@ commands:
                       - v4c-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
             - restore_cache:
                   keys:
-                      - v4b-<< pipeline.parameters.wireit_cache_name >>-{{ arch }}-{{ checksum "first-gen/package.json" }}-
+                      - v4b-<< pipeline.parameters.wireit_cache_name >>-{{ arch }}-{{ checksum "1st-gen/package.json" }}-
             - run:
                   name: Installing Dependencies
                   command: |
@@ -75,8 +75,8 @@ commands:
                   key: v4c-dependencies-{{ arch }}-{{ checksum "yarn.lock" }}
             - save_cache:
                   paths:
-                      - first-gen/.wireit
-                  key: v4b-wireit-{{ arch }}-{{ checksum "first-gen/package.json" }}-{{ epoch }}
+                      - 1st-gen/.wireit
+                  key: v4b-wireit-{{ arch }}-{{ checksum "1st-gen/package.json" }}-{{ epoch }}
             - attach_workspace:
                   at: /
     run-regressions:
@@ -100,8 +100,8 @@ commands:
             - run:
                   name: Count baseline images
                   command: |
-                      mkdir -p first-gen/test/visual/screenshots-baseline
-                      baseline_count=$(find first-gen/test/visual/screenshots-baseline -type f | wc -l)
+                      mkdir -p 1st-gen/test/visual/screenshots-baseline
+                      baseline_count=$(find 1st-gen/test/visual/screenshots-baseline -type f | wc -l)
                       echo "Found $baseline_count baseline images"
                       echo $baseline_count > count_start.txt
                   #   if [ $baseline_count -eq 0 ]; then
@@ -115,11 +115,11 @@ commands:
                       yarn workspace @spectrum-web-components/1st-gen test:ci --config web-test-runner.config.vrt.js --group vrt-<< parameters.regression_system >>-<< parameters.regression_color >>-<< parameters.regression_scale >>-<< parameters.regression_dir >>
             # store results and artifacts before rearranging things for the new cache.
             - store_test_results:
-                  path: /root/project/first-gen/results/
+                  path: /root/project/1st-gen/results/
             - run:
                   when: on_success
                   name: Count current images
-                  command: find first-gen/test/visual/screenshots-actual/updates -type f | wc -l > count_end.txt
+                  command: find 1st-gen/test/visual/screenshots-actual/updates -type f | wc -l > count_end.txt
             # prevent removing regression tests without requiring a new golden cache
             - run:
                   when: on_success
@@ -134,7 +134,7 @@ commands:
                   name: Create review site
                   command: |
                       branch=$(git symbolic-ref --short HEAD)
-                      cd first-gen && node test/visual/review.js --branch=$branch --commit=<< pipeline.git.revision >> --system="<< parameters.regression_system >> << parameters.regression_color >> << parameters.regression_scale >> << parameters.regression_dir >>" && yarn rollup -c test/visual/rollup.config.js
+                      cd 1st-gen && node test/visual/review.js --branch=$branch --commit=<< pipeline.git.revision >> --system="<< parameters.regression_system >> << parameters.regression_color >> << parameters.regression_scale >> << parameters.regression_dir >>" && yarn rollup -c test/visual/rollup.config.js
             - install-azcopy
             - run:
                   when: always
@@ -181,11 +181,11 @@ commands:
                       combination="<< parameters.regression_system >>-<< parameters.regression_color >>-<< parameters.regression_scale >>-<< parameters.regression_dir >>"
 
                       # Prepare files for deployment
-                      cp first-gen/projects/documentation/content/favicon.ico first-gen/test/visual/ || echo "Failed to copy favicon"
+                      cp 1st-gen/projects/documentation/content/favicon.ico 1st-gen/test/visual/ || echo "Failed to copy favicon"
 
                       # Upload VRT results to Azure Blob Storage
                       echo "Uploading VRT results to ${PR_HASH}/${combination}/"
-                      azcopy copy "first-gen/test/visual/*" \
+                      azcopy copy "1st-gen/test/visual/*" \
                         "https://swcpreviews.blob.core.windows.net/\$web/${PR_HASH}/${combination}/" \
                         --recursive \
                         --from-to LocalBlob
@@ -199,18 +199,18 @@ commands:
             - run:
                   when: always
                   command: |
-                      rm -rf first-gen/test/visual/screenshots-baseline
-                      cp -R first-gen/test/visual/screenshots-actual/updates first-gen/test/visual/screenshots-baseline
+                      rm -rf 1st-gen/test/visual/screenshots-baseline
+                      cp -R 1st-gen/test/visual/screenshots-actual/updates 1st-gen/test/visual/screenshots-baseline
             - save_cache:
                   when: always
                   name: Build Golden Images Revision Cache
                   paths:
-                      - first-gen/test/visual/screenshots-baseline
+                      - 1st-gen/test/visual/screenshots-baseline
                   key: v2-golden-images-{{ .Revision }}-<< parameters.regression_system >>-<< parameters.regression_color >>-<< parameters.regression_scale >>-<< parameters.regression_dir >>-{{ epoch }}
             - save_cache:
                   name: Build Golden Images Branch Cache
                   paths:
-                      - first-gen/test/visual/screenshots-baseline
+                      - 1st-gen/test/visual/screenshots-baseline
                   key: v2-golden-images-{{ .Branch }}-<< parameters.regression_system >>-<< parameters.regression_color >>-<< parameters.regression_scale >>-<< parameters.regression_dir >>-{{ epoch }}
 
 jobs:
@@ -223,12 +223,12 @@ jobs:
             - run:
                   name: Run chromium tests
                   command: |
-                      TEST=$(circleci tests glob "first-gen/{packages,tools}/*/test/*.test.js" | grep -v ".*-memory\.test\.js$" | circleci tests split --split-by=timings | sed 's/first-gen\///')
+                      TEST=$(circleci tests glob "1st-gen/{packages,tools}/*/test/*.test.js" | grep -v ".*-memory\.test\.js$" | circleci tests split --split-by=timings | sed 's/1st-gen\///')
                       yarn workspace @spectrum-web-components/1st-gen test:start --files $TEST --config ./web-test-runner.config.ci-chromium.js --group unit-ci
             - store_test_results:
-                  path: /root/project/first-gen/results/
+                  path: /root/project/1st-gen/results/
             - store_artifacts:
-                  path: first-gen/coverage
+                  path: 1st-gen/coverage
 
     test-chromium-coverage:
         executor: node
@@ -239,7 +239,7 @@ jobs:
                   name: Run chromium tests with coverage
                   command: yarn workspace @spectrum-web-components/1st-gen test:focus unit --config web-test-runner.config.ci-chromium.js --coverage
             - store_test_results:
-                  path: /root/project/first-gen/results/
+                  path: /root/project/1st-gen/results/
 
     test-chromium-memory:
         executor: node
@@ -250,7 +250,7 @@ jobs:
             - run:
                   name: Run memory tests
                   command: |
-                      TEST=$(circleci tests glob "first-gen/{packages,tools}/*/test/*-memory.test.js" | grep -v "packages/color-.*/test/.*-memory\.test\.js" | grep -v "tools/grid/test/.*-memory\.test\.js" | circleci tests split --split-by=timings | sed 's/first-gen\///')
+                      TEST=$(circleci tests glob "1st-gen/{packages,tools}/*/test/*-memory.test.js" | grep -v "packages/color-.*/test/.*-memory\.test\.js" | grep -v "tools/grid/test/.*-memory\.test\.js" | circleci tests split --split-by=timings | sed 's/1st-gen\///')
                       echo $TEST
                       yarn workspace @spectrum-web-components/1st-gen test:start --files $TEST --config web-test-runner.config.ci-chromium-memory.js --group unit-ci
             - store_test_results:
@@ -265,7 +265,7 @@ jobs:
             - run:
                   name: Run firefox tests
                   command: |
-                      TEST=$(circleci tests glob "first-gen/{packages,tools}/*/test/*.test.js" | grep -v ".*-memory\.test\.js$" | circleci tests split --split-by=timings | sed 's/first-gen\///')
+                      TEST=$(circleci tests glob "1st-gen/{packages,tools}/*/test/*.test.js" | grep -v ".*-memory\.test\.js$" | circleci tests split --split-by=timings | sed 's/1st-gen\///')
                       yarn workspace @spectrum-web-components/1st-gen test:start --files $TEST --config web-test-runner.config.ci-firefox.js --group unit-ci
             - store_test_results:
                   path: /root/project/results/
@@ -279,7 +279,7 @@ jobs:
             - run:
                   name: Run webkit tests
                   command: |
-                      TEST=$(circleci tests glob "first-gen/{packages,tools}/*/test/*.test.js" | grep -v ".*-memory\.test\.js$" | circleci tests split --split-by=timings | sed 's/first-gen\///')
+                      TEST=$(circleci tests glob "1st-gen/{packages,tools}/*/test/*.test.js" | grep -v ".*-memory\.test\.js$" | circleci tests split --split-by=timings | sed 's/1st-gen\///')
                       yarn workspace @spectrum-web-components/1st-gen test:start --files $TEST --config web-test-runner.config.ci-webkit.js --group unit-ci
             - store_test_results:
                   path: /root/project/results/
@@ -294,7 +294,7 @@ jobs:
                   command: yarn workspace @spectrum-web-components/1st-gen docs:analyze
             - run:
                   name: Move CEM to Storybook directory
-                  command: cp first-gen/projects/documentation/custom-elements.json first-gen/storybook/
+                  command: cp 1st-gen/projects/documentation/custom-elements.json 1st-gen/storybook/
             - run:
                   name: Build documentation with path prefix
                   command: echo "SWC_DIR=beta/docs" >> $BASH_ENV
@@ -310,14 +310,14 @@ jobs:
                   command: |
                       # Upload documentation to beta path
                       echo "Uploading documentation to beta/docs/"
-                      azcopy copy "first-gen/projects/documentation/dist/*" \
+                      azcopy copy "1st-gen/projects/documentation/dist/*" \
                         "https://swcpreviews.blob.core.windows.net/\$web/beta/docs/" \
                         --recursive \
                         --from-to LocalBlob
 
                       # Upload Storybook to beta path
                       echo "Uploading Storybook to beta/docs/storybook/"
-                      azcopy copy "first-gen/storybook-static/*" \
+                      azcopy copy "1st-gen/storybook-static/*" \
                         "https://swcpreviews.blob.core.windows.net/\$web/beta/docs/storybook/" \
                         --recursive \
                         --from-to LocalBlob
@@ -341,8 +341,8 @@ jobs:
             - run:
                   name: Count baseline images
                   command: |
-                      mkdir -p first-gen/test/visual/screenshots-baseline
-                      baseline_count=$(find first-gen/test/visual/screenshots-baseline -type f | wc -l)
+                      mkdir -p 1st-gen/test/visual/screenshots-baseline
+                      baseline_count=$(find 1st-gen/test/visual/screenshots-baseline -type f | wc -l)
                       echo "Found $baseline_count baseline images"
                       echo $baseline_count > count_start.txt
                   #   if [ $baseline_count -eq 0 ]; then
@@ -356,11 +356,11 @@ jobs:
                       yarn workspace @spectrum-web-components/1st-gen test:ci --config web-test-runner.config.vrt.js --group vrt-hcm
             # store results and artifacts before rearranging things for the new cache.
             - store_test_results:
-                  path: /root/project/first-gen/results/
+                  path: /root/project/1st-gen/results/
             - run:
                   when: on_success
                   name: Count current images
-                  command: find first-gen/test/visual/screenshots-actual/updates -type f | wc -l > count_end.txt
+                  command: find 1st-gen/test/visual/screenshots-actual/updates -type f | wc -l > count_end.txt
             # prevent removing regression tests without requiring a new golden cache
             - run:
                   when: on_success
@@ -375,7 +375,7 @@ jobs:
                   name: Create review site
                   command: |
                       branch=$(git symbolic-ref --short HEAD)
-                      cd first-gen && node test/visual/review.js --branch=$branch --commit=<< pipeline.git.revision >> --system="hcm" && yarn rollup -c test/visual/rollup.config.js
+                      cd 1st-gen && node test/visual/review.js --branch=$branch --commit=<< pipeline.git.revision >> --system="hcm" && yarn rollup -c test/visual/rollup.config.js
             - install-azcopy
             - run:
                   when: always
@@ -419,11 +419,11 @@ jobs:
                       fi
 
                       # Prepare files for deployment
-                      cp first-gen/projects/documentation/content/favicon.ico first-gen/test/visual/
+                      cp 1st-gen/projects/documentation/content/favicon.ico 1st-gen/test/visual/
 
                       # Upload HCM VRT results to Azure Blob Storage
                       echo "Uploading HCM VRT to ${PR_HASH}/hcm/"
-                      azcopy copy "first-gen/test/visual/*" \
+                      azcopy copy "1st-gen/test/visual/*" \
                         "https://swcpreviews.blob.core.windows.net/\$web/${PR_HASH}/hcm/" \
                         --recursive \
                         --from-to LocalBlob
@@ -437,18 +437,18 @@ jobs:
             - run:
                   when: always
                   command: |
-                      rm -rf first-gen/test/visual/screenshots-baseline
-                      cp -R first-gen/test/visual/screenshots-actual/updates first-gen/test/visual/screenshots-baseline
+                      rm -rf 1st-gen/test/visual/screenshots-baseline
+                      cp -R 1st-gen/test/visual/screenshots-actual/updates 1st-gen/test/visual/screenshots-baseline
             - save_cache:
                   when: always
                   name: Build Golden Images Revision Cache
                   paths:
-                      - first-gen/test/visual/screenshots-baseline
+                      - 1st-gen/test/visual/screenshots-baseline
                   key: v2-golden-images-{{ .Revision }}-hcm-{{ epoch }}
             - save_cache:
                   name: Build Golden Images Branch Cache
                   paths:
-                      - first-gen/test/visual/screenshots-baseline
+                      - 1st-gen/test/visual/screenshots-baseline
                   key: v2-golden-images-{{ .Branch }}-hcm-{{ epoch }}
 
     visual:
