ci: upgraded to azure from netlify

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -100,8 +100,8 @@ commands:
             - run:
                   name: Install Azure CLI and Static Web Apps CLI
                   command: |
-                        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
-                        npm install -g @azure/static-web-apps-cli
+                      curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
+                      npm install -g @azure/static-web-apps-cli
             - run:
                   when: always
                   name: Publish review site
@@ -129,10 +129,10 @@ commands:
                             echo "Deploy failed, retrying ($attempt/$max_attempts)..."
                             sleep 10
                         fi
-                    done
+                        done
 
-                    echo "Deployment failed after $max_attempts attempts."
-                    exit 1  
+                        echo "Deployment failed after $max_attempts attempts."
+                        exit 1
 
             # move "updated" screenshot into the baseline directory before making the new cache
             - run:
@@ -251,15 +251,15 @@ jobs:
             - run:
                   name: Deploy Documentation Site to Azure Static Web Apps
                   command: |
-                    branch=$(git symbolic-ref --short HEAD)
-                    branch=$(npx slugify-cli $branch)
-                    az login --identity || echo "Skipping login for GitHub token-based deploy"
-                    az staticwebapp upload \
-                        --name my-docs-site \
-                        --resource-group swc-previews \
-                        --source projects/documentation/dist \
-                        --token $AZURE_DOCS_STATIC_WEB_APPS_TOKEN \
-                        --output none
+                      branch=$(git symbolic-ref --short HEAD)
+                      branch=$(npx slugify-cli $branch)
+                      az login --identity || echo "Skipping login for GitHub token-based deploy"
+                      az staticwebapp upload \
+                          --name my-docs-site \
+                          --resource-group swc-previews \
+                          --source projects/documentation/dist \
+                          --token $AZURE_DOCS_STATIC_WEB_APPS_TOKEN \
+                          --output none
 
     beta-docs:
         executor: node
@@ -334,32 +334,31 @@ jobs:
             - run:
                   name: Deploy Visual Regression Site to Azure
                   command: |
-                    branch=$(git symbolic-ref --short HEAD)
-                    hash=$(echo -n $branch-<< parameters.regression_system >>-<< parameters.regression_color >>-<< parameters.regression_scale >>-<< parameters.regression_dir >> | md5sum | cut -c 1-32)
-                    echo "Azure deployment hash: $hash"
+                      branch=$(git symbolic-ref --short HEAD)
+                      hash=$(echo -n $branch-hcm | md5sum | cut -c 1-32)
+                      echo "Azure deployment hash: $hash"
 
-                    max_attempts=3
-                    attempt=0
+                      max_attempts=3
+                      attempt=0
 
-                    while [ $attempt -lt $max_attempts ]; do
-                        if az staticwebapp upload \
-                            --name my-visual-regression-site \
-                            --resource-group swc-previews \
-                            --source test/visual \
-                            --token $AZURE_VR_STATIC_WEB_APPS_TOKEN \
-                            --output none; then
-                            echo "Deployment successful!"
-                            exit 0
-                        else
-                            attempt=$((attempt + 1))
-                            echo "Deploy failed, retrying ($attempt/$max_attempts)..."
-                            sleep 10
-                        fi
-                    done
+                      while [ $attempt -lt $max_attempts ]; do
+                          if az staticwebapp upload \
+                              --name my-visual-regression-site \
+                              --resource-group swc-previews \
+                              --source test/visual \
+                              --token $AZURE_VR_STATIC_WEB_APPS_TOKEN \
+                              --output none; then
+                              echo "Deployment successful!"
+                              exit 0
+                          else
+                              attempt=$((attempt + 1))
+                              echo "Deploy failed, retrying ($attempt/$max_attempts)..."
+                              sleep 10
+                          fi
+                      done
 
-                    echo "Deployment failed after $max_attempts attempts."
-                    exit 1  
-
+                      echo "Deployment failed after $max_attempts attempts."
+                      exit 1
 
             # move "updated" screenshot into the baseline directory before making the new cache
             - run:
